name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  build:
    strategy:
      matrix:
        compiler:
        - {
            name: "x86_64-8.1.0-release-posix-seh-rt_v6-rev0",
            url: "https://github.com/dirkarnez/cpp-tools/raw/main/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z",
            generator: "MinGW Makefiles",
            on: "windows-latest"
          }
        # - {
        #     name: "winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1",
        #     url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-12.0.1-9.0.0-r1/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip",
        #     generator: "MinGW Makefiles",
        #     on: "windows-latest"
        #   }
        # - {
        #     name: "msvc2019",
        #     generator:  "Visual Studio 16 2019",
        #     extra: "-A x64",
        #     on: "windows-2019"
        #   }
        # - {
        #     name: "msvc2022",
        #     generator:  "Visual Studio 17 2022",
        #     extra: "-A x64",
        #     on: "windows-latest"
        #   }

    runs-on: ${{ matrix.compiler.on }}
    env:
      libraryName: serial
      cmakeInstallationPath: serial-installation
      tagName: v5.3.1
    steps:
      - uses: actions/checkout@v4
        with:
          repository: karthickai/serial
          path: ${{ env.libraryName }}
          submodules: true
# ref: ${{ env.tagName }}

      - name: download compiler
        if: ${{  matrix.compiler.url }}
        shell: cmd
        run: |
          curl ${{ matrix.compiler.url }} -L --output compiler &&^
          7z.exe x compiler
          
      - name: curl cmake-3.24.0-windows-x86_64.zip
        shell: cmd
        run: curl https://github.com/Kitware/CMake/releases/download/v3.24.0/cmake-3.24.0-windows-x86_64.zip -L --output cmake-3.24.0-windows-x86_64.zip && dir && 7z.exe x cmake-3.24.0-windows-x86_64.zip

      - name: curl PortableGit-2.38.1-64-bit.7z.exe
        shell: cmd
        run: curl https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/PortableGit-2.38.1-64-bit.7z.exe -L --output PortableGit-2.38.1-64-bit.7z.exe && dir && 7z.exe x PortableGit-2.38.1-64-bit.7z.exe -o"PortableGit-2.38.1-64-bit"
      
      - shell: cmd
        run: |
          cd "${{ env.libraryName }}" &&^
          dir &&^
          "${{ github.workspace }}\PortableGit-2.38.1-64-bit\usr\bin\sed.exe" -i "s/set\s\+(BOOST_.*//g" CMakeLists.txt &&^
          "${{ github.workspace }}\PortableGit-2.38.1-64-bit\usr\bin\sed.exe" -i "s/target_link_libraries(serial\s\+\${Boost_LIBRARIES})/target_link_libraries(serial ws2_32 \${Boost_LIBRARIES})/g" CMakeLists.txt &&^
          type CMakeLists.txt
          
      - shell: cmd
        run: |
          curl "https://github.com/dirkarnez/boost-prebuilt/releases/download/v1.72.0/boost-v1.72.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip" -L -O -J &&^
          7z.exe x boost-v1.72.0-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -o"boost-v1.72.0-mingw64-x86_64-posix-seh-rev0-8.1.0"
          
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: cmd
        run: |
            set PATH=^
            ${{ github.workspace }}\mingw64;^
            ${{ github.workspace }}\mingw64\bin;^
            ${{ github.workspace }}\cmake-3.24.0-windows-x86_64\bin;
            set CD_LINUX=%CD:\=/%
            cd "${{ env.libraryName }}" &&^
            cmake.exe -G "${{ matrix.compiler.generator }}" ${{ matrix.compiler.extra }} ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DBUILD_SHARED_LIBS=OFF ^
            -DBoost_COMPILER=mgw81 ^
            -DBoost_NO_SYSTEM_PATHS=TRUE ^
            -DBoost_USE_STATIC_LIBS=TRUE ^
            -DBoost_USE_STATIC_RUNTIME=ON ^
            -DCMAKE_EXE_LINKER_FLAGS="-static" ^
            -DBOOST_ROOT="%CD_LINUX%/boost-v1.72.0-mingw64-x86_64-posix-seh-rev0-8.1.0/lib/cmake/Boost-1.72.0" ^
            -DCMAKE_INSTALL_PREFIX="cmake-build/${{ env.cmakeInstallationPath }}" -B./cmake-build &&^
            cd cmake-build && cmake --build . --config Release && cmake --install . && dir /s
 
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          path: |
            serial.exe
          directory: "${{ env.libraryName }}/cmake-build"
          filename: "${{ env.libraryName }}-${{ github.ref_name }}-${{ matrix.compiler.name }}.zip"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.libraryName }}/cmake-build/${{ env.libraryName }}-${{ github.ref_name }}-${{ matrix.compiler.name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
